version: '3'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.14
    ports:
      - "4580:80"
      - "45443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
  kanboard_plugins:
    driver: local
    driver_opts:
      type: none
      device: $PWD/plugins
      o: bind
  kanboard_ssl: